### ISSUE TITLE
refactor: 회원가입 프로세스 2단계로 분리

### ISSUE THREAD

**Issue by LeeKing2017** [prj154654168/Sooum-BE#158]
### 이슈 내용(Description)

회원가입 프로세스 2단계로 분리

### 상세 내용(Details)

- 회원가입 프로세스를 약관동의 전과 후로 분리
- 약관동의 전에 없는 데이터는 dummy 데이터 넣어주세요

**Comment by KoungQ** [comment]
약관동의 후 멤버 더미데이터 생성 후 회원가입 완료하면 수정하는 방식
